name: "AWS Deployment Setup"
description: "AWS CDK ë°°í¬ë¥¼ ìœ„í•œ í™˜ê²½ì„ ì„¤ì •í•©ë‹ˆë‹¤"

inputs:
  aws-region:
    description: "AWS ë¦¬ì „"
    required: false
    default: "us-east-1"
  aws-account-id:
    description: "AWS ê³„ì • ID"
    required: true
  environment:
    description: "ë°°í¬ í™˜ê²½ (dev|test|prod)"
    required: true
  node-version:
    description: "Node.js ë²„ì „"
    required: false
    default: "20"
  pnpm-version:
    description: "pnpm ë²„ì „"
    required: false
    default: "10.13.1"

outputs:
  cdk-version:
    description: "ì„¤ì¹˜ëœ CDK ë²„ì „"
    value: ${{ steps.cdk-info.outputs.version }}
  bootstrap-status:
    description: "CDK ë¶€íŠ¸ìŠ¤íŠ¸ëž© ìƒíƒœ"
    value: ${{ steps.bootstrap-check.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js and pnpm
      uses: ./.github/actions/setup-node-pnpm
      with:
        node-version: ${{ inputs.node-version }}
        pnpm-version: ${{ inputs.pnpm-version }}
        install-dependencies: "true"
        cache-key-suffix: "cdk-${{ inputs.environment }}"

    - name: AWS í™˜ê²½ ì •ë³´ ì¶œë ¥
      shell: bash
      run: |
        echo "ðŸŒ AWS ë°°í¬ í™˜ê²½ ì„¤ì •"
        echo "â”œâ”€ ë¦¬ì „: ${{ inputs.aws-region }}"
        echo "â”œâ”€ ê³„ì • ID: ${{ inputs.aws-account-id }}"
        echo "â”œâ”€ í™˜ê²½: ${{ inputs.environment }}"
        echo "â””â”€ CDK ì»¨í…ìŠ¤íŠ¸: environment=${{ inputs.environment }}"

    - name: CDK ì •ë³´ í™•ì¸
      id: cdk-info
      shell: bash
      working-directory: apps/server/infrastructure
      run: |
        CDK_VERSION=$(npx cdk --version 2>/dev/null || echo "ì„¤ì¹˜ë˜ì§€ ì•ŠìŒ")
        echo "version=$CDK_VERSION" >> $GITHUB_OUTPUT
        echo "ðŸ“¦ CDK ë²„ì „: $CDK_VERSION"

    - name: CDK ë¶€íŠ¸ìŠ¤íŠ¸ëž© ìƒíƒœ í™•ì¸
      id: bootstrap-check
      shell: bash
      run: |
        echo "ðŸ” CDK ë¶€íŠ¸ìŠ¤íŠ¸ëž© ìƒíƒœ í™•ì¸ ì¤‘..."

        # CDKToolkit ìŠ¤íƒ ì¡´ìž¬ ì—¬ë¶€ í™•ì¸
        if aws cloudformation describe-stacks \
           --stack-name CDKToolkit \
           --region ${{ inputs.aws-region }} \
           --query 'Stacks[0].StackStatus' \
           --output text >/dev/null 2>&1; then
          echo "status=bootstrapped" >> $GITHUB_OUTPUT
          echo "âœ… CDK ë¶€íŠ¸ìŠ¤íŠ¸ëž© ì™„ë£Œë¨"
        else
          echo "status=not-bootstrapped" >> $GITHUB_OUTPUT
          echo "âš ï¸ CDK ë¶€íŠ¸ìŠ¤íŠ¸ëž© í•„ìš”"
        fi

    - name: CDK ë¶€íŠ¸ìŠ¤íŠ¸ëž© (í•„ìš”ì‹œ)
      if: steps.bootstrap-check.outputs.status == 'not-bootstrapped'
      shell: bash
      working-directory: apps/server/infrastructure
      run: |
        echo "ðŸš€ CDK ë¶€íŠ¸ìŠ¤íŠ¸ëž© ì‹¤í–‰ ì¤‘..."
        npx cdk bootstrap \
          aws://${{ inputs.aws-account-id }}/${{ inputs.aws-region }} \
          --context environment=${{ inputs.environment }} \
          --require-approval never
        echo "âœ… CDK ë¶€íŠ¸ìŠ¤íŠ¸ëž© ì™„ë£Œ"

    - name: CDK í•©ì„± (í…œí”Œë¦¿ ìƒì„±)
      shell: bash
      working-directory: apps/server/infrastructure
      run: |
        echo "ðŸ”¨ CloudFormation í…œí”Œë¦¿ í•©ì„± ì¤‘..."
        npx cdk synth \
          --context environment=${{ inputs.environment }} \
          --quiet
        echo "âœ… í…œí”Œë¦¿ í•©ì„± ì™„ë£Œ"

    - name: CDK Diff (ë³€ê²½ì‚¬í•­ í™•ì¸)
      shell: bash
      working-directory: apps/server/infrastructure
      run: |
        echo "ðŸ“‹ ë°°í¬ ë³€ê²½ì‚¬í•­ í™•ì¸ ì¤‘..."
        echo "::group::CDK Diff Output"
        npx cdk diff \
          --context environment=${{ inputs.environment }} \
          --require-approval never || true
        echo "::endgroup::"
        echo "âœ… ë³€ê²½ì‚¬í•­ í™•ì¸ ì™„ë£Œ"

    - name: ë°°í¬ ì¤€ë¹„ ìƒíƒœ ìš”ì•½
      shell: bash
      run: |
        echo "## ðŸš€ AWS CDK ë°°í¬ ì¤€ë¹„ ì™„ë£Œ" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| í•­ëª© | ê°’ |" >> $GITHUB_STEP_SUMMARY
        echo "|------|-----|" >> $GITHUB_STEP_SUMMARY
        echo "| AWS ë¦¬ì „ | ${{ inputs.aws-region }} |" >> $GITHUB_STEP_SUMMARY
        echo "| AWS ê³„ì • | ${{ inputs.aws-account-id }} |" >> $GITHUB_STEP_SUMMARY
        echo "| ë°°í¬ í™˜ê²½ | ${{ inputs.environment }} |" >> $GITHUB_STEP_SUMMARY
        echo "| CDK ë²„ì „ | ${{ steps.cdk-info.outputs.version }} |" >> $GITHUB_STEP_SUMMARY
        echo "| ë¶€íŠ¸ìŠ¤íŠ¸ëž© ìƒíƒœ | ${{ steps.bootstrap-check.outputs.status }} |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "ë°°í¬ê°€ ì¤€ë¹„ë˜ì—ˆìŠµë‹ˆë‹¤! ðŸŽ‰" >> $GITHUB_STEP_SUMMARY
